import { AutoMap } from '@automapper/classes';
import { attribute, autoGeneratedHashKey, rangeKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table('usersTable')
export class User {
  @autoGeneratedHashKey()
  @AutoMap()
  id: string;

  @attribute()
  @AutoMap()
  name: string;

  @attribute()
  @AutoMap()
  type: string;

  @rangeKey({defaultProvider: () => new Date()})
  @AutoMap()
  createdAt: Date;

  @attribute()
  @AutoMap()
  updatedAt: Date;
}
